---
title: "R Notebook"
output: html_notebook
---

```{r}

library(tidyverse)
library(readxl)
library(here)
library(janitor)
```

```{r}
candy_2015 <- read_excel(here("raw_data/boing-boing-candy-2015.xlsx"))
candy_2016 <- read_excel(here("raw_data/boing-boing-candy-2016.xlsx"))
candy_2017 <- read_excel(here("raw_data/boing-boing-candy-2017.xlsx"))
```

```{r}
candy_2015 <- clean_names(candy_2015)
candy_2016 <- clean_names(candy_2016)
candy_2017 <- clean_names(candy_2017)
```



```{r}
removed_columns_candy_2015 <- select(candy_2015,-c(
  please_leave_any_remarks_or_comments_regarding_your_choices:
    sea_salt_flavored_stuff_probably_chocolate_since_this_is_the_it_flavor_of_the_year,
  which_day_do_you_prefer_friday_or_sunday:
    please_estimate_the_degrees_of_separation_you_have_from_the_following_folks_beyonce_knowles
))%>%
  rename(going_trick_or_treating = are_you_going_actually_going_trick_or_treating_yourself) %>%
  rename(age = how_old_are_you) %>%
  rename(free_restaurant_candy =
          candy_that_is_clearly_just_the_stuff_given_out_for_free_at_restaurants) %>%
  rename( hfcs_vials = 
          vials_of_pure_high_fructose_corn_syrup_for_main_lining_into_your_vein ) %>%
  rename( marshmallow_circus_peanuts = 
            those_odd_marshmallow_circus_peanut_things) %>%
  rename( chick_o_sticks = chick_o_sticks_we_don_t_know_what_that_is) %>%
  rename( `100_grand_bar` = x100_grand_bar) %>%
  rename( boxo_raisins = box_o_raisins)


```
# pivot/add columns
#used pivot to make a new candy and ratings column
#added columns in prep for binding datasets
#changed rating values to all lowercase


```{r}
candy_2015_pivot <- removed_columns_candy_2015 %>%
  mutate(id = row_number())%>%
    pivot_longer(c(butterfinger:necco_wafers),
                 names_to = "candy", values_to = "rating") %>%
    mutate(
        year = 2015,
        gender = NA,
        country = NA,
        rating = tolower(rating)
    )%>%
  mutate(id = str_c(year, id, sep = "_"))%>%
  select(-timestamp)


```



```{r}
removed_columns_candy_2016 <- select(candy_2016, -c(
  please_list_any_items_not_included_above_that_give_you_joy:
    york_peppermint_patties_ignore,
  which_state_province_county_do_you_live_in
  ))%>%
  rename(going_trick_or_treating = are_you_going_actually_going_trick_or_treating_yourself)%>%
  rename(age = how_old_are_you)%>%
  rename(gender = your_gender)%>%
  rename(country = which_country_do_you_live_in) %>%
  rename(free_restaurant_candy =
          candy_that_is_clearly_just_the_stuff_given_out_for_free_at_restaurants) %>%
  rename( hfcs_vials = 
          vials_of_pure_high_fructose_corn_syrup_for_main_lining_into_your_vein ) %>%
  rename( sourpatch_kids = sourpatch_kids_i_e_abominations_of_nature) %>%
  rename( marshmallow_circus_peanuts = 
            those_odd_marshmallow_circus_peanut_things) %>%
  rename( chick_o_sticks = chick_o_sticks_we_don_t_know_what_that_is) %>%
  rename( `100_grand_bar` = x100_grand_bar)


```


```{r}
candy_2016_pivot <- removed_columns_candy_2016 %>%
  mutate(id = row_number())%>%
    pivot_longer(c(`100_grand_bar`:york_peppermint_patties),
                 names_to = "candy", values_to = "rating") %>%
    mutate(
        year = 2016,
        rating = tolower(rating)
    )%>%
    mutate(id = str_c(year, id, sep = "_"))%>%
  select(-timestamp)

names(candy_2016_pivot)
```


#2017

## removing the question number at the start of each column
```{r}
(names(candy_2017) = gsub(pattern = "q[0-9]*_",
                           replacement = "",
                           x = names(candy_2017)))
```

```{r}
removed_columns_candy_2017 <- select(candy_2017, -c(
  joy_other:click_coordinates_x_y,
  state_province_county_etc
  ))%>%
  rename(going_trick_or_treating = going_out)%>%
  rename(free_restaurant_candy =
          candy_that_is_clearly_just_the_stuff_given_out_for_free_at_restaurants) %>%
  rename( hfcs_vials = 
          vials_of_pure_high_fructose_corn_syrup_for_main_lining_into_your_vein ) %>%
  rename( sourpatch_kids = sourpatch_kids_i_e_abominations_of_nature) %>%
  rename( marshmallow_circus_peanuts = 
            those_odd_marshmallow_circus_peanut_things) %>%
  rename( chick_o_sticks = chick_o_sticks_we_don_t_know_what_that_is)%>%
  rename( mary_janes = 
          anonymous_brown_globs_that_come_in_black_and_orange_wrappers_a_k_a_mary_janes)

```

```{r}
candy_2017_pivot <- removed_columns_candy_2017 %>%
    mutate(id = row_number())%>%
    pivot_longer(c(`100_grand_bar`:york_peppermint_patties),
                 names_to = "candy", values_to = "rating") %>%
    mutate(
        year = 2017,
        rating = tolower(rating)
    )%>%
    mutate(id = str_c(year, id, sep = "_"))%>%
  select(-internal_id)

```

```{r}
all_candy <- bind_rows(candy_2015_pivot, candy_2016_pivot, candy_2017_pivot)

```

```{r}
usa_names <- str_c("usa", "state", "merica", "united s",
                   "u.s", "us", "murica", "aayy", "alaska", "calif",
                   "trump", "rika", "carolina", "new york", "pitts",
                   "amerca", "cascadia", "new jersey", sep = "|"
                   )

canada_names <- str_c("canae", "canuck", "can", sep = "|")

uk_names <- str_c("uk", "united kin", "scotland", "endland",
                  "england", "god's country", "u.k", sep = "|" )

other_names <- str_c("united states", "uk", "canada", sep = "|")

all_candy_country <- all_candy %>%
  mutate(country = tolower(country),
         country = if_else(str_detect(country, usa_names),
                           "united states", country),
         country = if_else(str_detect(country, canada_names),
                           "canada", country),
         country = if_else(str_detect(country, uk_names),
                           "uk", country),
         country = if_else(!str_detect(country, other_names),
                           "other", country),
         )

all_candy_country <- all_candy_country%>%
  mutate(country = replace_na(country, "other"))

```

```{r}
all_candy_country$age <- as.numeric(all_candy_country$age)
all_candy_country <- all_candy_country %>%
mutate(age = if_else( age %in% 4:90, age, as.numeric(NA)))

```

```{r}
remove_candy <- str_c("vicodin", "bread", "kale_smoothie", "chardonnay",
                      "acetam", "season", "physical", "cash", "healthy_fruit", 
                      "board_game", "comics", "glow_sticks", "blue", "red",
                      "green", "independent", "abstained", "lapel", "dental",
                      "glow", "chalk", "third",
                      sep = "|")

all_candy_country <- all_candy_country%>%
  filter(!str_detect(candy, remove_candy ))
  
  

all_candy_country%>%
  group_by(candy)%>%
  summarise(count=n())

```

